on:
  push:
    branches: [ main ]
    
jobs:
  List-Branches:
    runs-on: ubuntu-latest
    name: Job para listar Branches de repositório GitHub
    steps:
    - name: List Branches Docker Action
      uses: geovanams/list-repos-msbuild@v1
      with:
        user: geovanams
        repo: public-repo
